In [1]:
file = open('data.txt','w')
file.write('this is done ')
file.close()

In [2]:
with open('data.txt','r') as f :
    k=f.read()
    print(k)

this is done 


In [3]:
file = open('data.txt','w')
file.write('hell\n')
file.write('of \n')
file.write('games\n')
file.close()

In [4]:
with open('data.txt','r') as f :
    k=f.read()
    print(k)

hell
of 
games



In [5]:
import datetime
datetime.date.today()

datetime.date(2022, 9, 23)

In [6]:
from datetime import date 
date.today()

datetime.date(2022, 9, 23)

In [7]:
pip --version

pip 22.2.2 from c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

Note: you may need to restart the kernel to use updated packages.


In [8]:
# python -m pip install -U pip to updrade 

In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [11]:
a= ['a','b','c','d','a']      #unique items once
np.unique(a)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [12]:
name = 'My ,name ,is ,kahsi'.split(' , ')

In [13]:
name

['My ,name ,is ,kahsi']

In [14]:
no= ['ca','la','ca']  
no.count('ca') # means how many times occur 

2

In [15]:
no.append('na') # add

In [16]:
no

['ca', 'la', 'ca', 'na']

# range 

In [17]:
for value in range (0,10):
    print(value)

0
1
2
3
4
5
6
7
8
9


In [18]:
for value in range (0,10,2):
    print(value)

0
2
4
6
8


In [19]:
# to square all no
square =[]
for x in range (2,50,5):
    square.append(x**2) # x ki power
square


[4, 49, 144, 289, 484, 729, 1024, 1369, 1764, 2209]

In [20]:
output= [i for i in range (2,100) if i%2==0]
output

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [21]:
!pip install numpy 


# Numpy

In [22]:
import numpy as np

In [23]:
# one_dimentional 
mylist = [1,2,3]
n= np.array(mylist)
n

array([1, 2, 3])

In [24]:
# multidimentional array 
list = np.array([[1,2,3],[1,2,3],[1,2,3]])
list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [28]:
#zero func
zero = np.zeros(100)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
#diagnol will be 1
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
b=np.arange(0,50)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
len(b)

50

In [33]:
b.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:

oo=np.linspace(0,7,10) # 0 to 7 equally space 20 parts 
oo

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [35]:
oo.resize(5,2)
oo

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [36]:
n=np.random.rand(3,3)
n

array([[0.15471211, 0.45726978, 0.04597391],
       [0.02915838, 0.11844265, 0.25732331],
       [0.54443782, 0.57974943, 0.90090768]])

In [37]:
k=np.random.randint(4,15,10)
k

array([11, 13, 12,  4,  7, 13,  6, 14,  9,  8])

In [38]:
k.reshape(5,2)

array([[11, 13],
       [12,  4],
       [ 7, 13],
       [ 6, 14],
       [ 9,  8]])

In [39]:
# 0 to 10 random no and aranging 4*3 column
tt=np.random.randint(0,10,(4,3))
tt

array([[4, 0, 8],
       [2, 0, 8],
       [4, 4, 9],
       [1, 2, 3]])

In [40]:
tt[2,0:2]    # row no 2 and col 0 ,1 pointed elements

array([4, 4])

In [41]:
tt>6

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False, False]])

# brodcasting

In [42]:
tt[tt>1]=1 # any no greater than 1 make tham 1 
tt

array([[1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
# creating copy
tt_copy=tt.copy()

In [44]:
tt_copy

array([[1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
import pandas as pd

In [46]:
data =pd.read_csv('Automobile.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Automobile.csv'

In [ ]:
data

symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std   
1            3                168  alfa-romero       gas        std   
2            1                168  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        88.6   
1               two  convertible          rwd           front        88.6   
2               two    hatchback          rwd           front        94.5   
3              four        sedan          fwd           front        99.8   
4              four        sedan          4wd           front        99.4   
..              ...          ...          ...             ...         ...   
196            four        sedan          rwd           front       109.1   
197            four        sedan          rwd           front       109.1   
198            four        sedan          rwd           front       109.1   
199            four        sedan          rwd           front       109.1   
200            four        sedan          rwd           front       109.1   

     ...  engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0    ...          130         mpfi  3.47    2.68               9.0        111   
1    ...          130         mpfi  3.47    2.68               9.0        111   
2    ...          152         mpfi  2.68    3.47               9.0        154   
3    ...          109         mpfi  3.19    3.40              10.0        102   
4    ...          136         mpfi  3.19    3.40               8.0        115   
..   ...          ...          ...   ...     ...               ...        ...   
196  ...          141         mpfi  3.78    3.15               9.5        114   
197  ...          141         mpfi  3.78    3.15               8.7        160   
198  ...          173         mpfi  3.58    2.87               8.8        134   
199  ...          145          idi  3.01    3.40              23.0        106   
200  ...          141         mpfi  3.78    3.15               9.5        114   

     peak_rpm city_mpg  highway_mpg  price  
0        5000       21           27  13495  
1        5000       21           27  16500  
2        5000       19           26  16500  
3        5500       24           30  13950  
4        5500       18           22  17450  
..        ...      ...          ...    ...  
196      5400       23           28  16845  
197      5300       19           25  19045  
198      5500       18           23  21485  
199      4800       26           27  22470  
200      5400       19           25  22625  

[201 rows x 26 columns]

In [ ]:
data.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [ ]:
data1=data.copy()

In [ ]:
# jo add kerwana ha wo left pa jasa mk
data1[['mk']]=data1[['make']]

In [ ]:
data1

symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std   
1            3                168  alfa-romero       gas        std   
2            1                168  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        88.6   
1               two  convertible          rwd           front        88.6   
2               two    hatchback          rwd           front        94.5   
3              four        sedan          fwd           front        99.8   
4              four        sedan          4wd           front        99.4   
..              ...          ...          ...             ...         ...   
196            four        sedan          rwd           front       109.1   
197            four        sedan          rwd           front       109.1   
198            four        sedan          rwd           front       109.1   
199            four        sedan          rwd           front       109.1   
200            four        sedan          rwd           front       109.1   

     ...  fuel_system  bore  stroke  compression_ratio horsepower peak_rpm  \
0    ...         mpfi  3.47    2.68                9.0        111     5000   
1    ...         mpfi  3.47    2.68                9.0        111     5000   
2    ...         mpfi  2.68    3.47                9.0        154     5000   
3    ...         mpfi  3.19    3.40               10.0        102     5500   
4    ...         mpfi  3.19    3.40                8.0        115     5500   
..   ...          ...   ...     ...                ...        ...      ...   
196  ...         mpfi  3.78    3.15                9.5        114     5400   
197  ...         mpfi  3.78    3.15                8.7        160     5300   
198  ...         mpfi  3.58    2.87                8.8        134     5500   
199  ...          idi  3.01    3.40               23.0        106     4800   
200  ...         mpfi  3.78    3.15                9.5        114     5400   

     city_mpg highway_mpg  price           mk  
0          21          27  13495  alfa-romero  
1          21          27  16500  alfa-romero  
2          19          26  16500  alfa-romero  
3          24          30  13950         audi  
4          18          22  17450         audi  
..        ...         ...    ...          ...  
196        23          28  16845        volvo  
197        19          25  19045        volvo  
198        18          23  21485        volvo  
199        26          27  22470        volvo  
200        19          25  22625        volvo  

[201 rows x 27 columns]

In [ ]:
data1.drop(['make'],axis=1) # axis =1 for column

symboling  normalized_losses fuel_type aspiration number_of_doors  \
0            3                168       gas        std             two   
1            3                168       gas        std             two   
2            1                168       gas        std             two   
3            2                164       gas        std            four   
4            2                164       gas        std            four   
..         ...                ...       ...        ...             ...   
196         -1                 95       gas        std            four   
197         -1                 95       gas      turbo            four   
198         -1                 95       gas        std            four   
199         -1                 95    diesel      turbo            four   
200         -1                 95       gas      turbo            four   

      body_style drive_wheels engine_location  wheel_base  length  ...  \
0    convertible          rwd           front        88.6   168.8  ...   
1    convertible          rwd           front        88.6   168.8  ...   
2      hatchback          rwd           front        94.5   171.2  ...   
3          sedan          fwd           front        99.8   176.6  ...   
4          sedan          4wd           front        99.4   176.6  ...   
..           ...          ...             ...         ...     ...  ...   
196        sedan          rwd           front       109.1   188.8  ...   
197        sedan          rwd           front       109.1   188.8  ...   
198        sedan          rwd           front       109.1   188.8  ...   
199        sedan          rwd           front       109.1   188.8  ...   
200        sedan          rwd           front       109.1   188.8  ...   

     engine_size  fuel_system  bore stroke compression_ratio  horsepower  \
0            130         mpfi  3.47   2.68               9.0         111   
1            130         mpfi  3.47   2.68               9.0         111   
2            152         mpfi  2.68   3.47               9.0         154   
3            109         mpfi  3.19   3.40              10.0         102   
4            136         mpfi  3.19   3.40               8.0         115   
..           ...          ...   ...    ...               ...         ...   
196          141         mpfi  3.78   3.15               9.5         114   
197          141         mpfi  3.78   3.15               8.7         160   
198          173         mpfi  3.58   2.87               8.8         134   
199          145          idi  3.01   3.40              23.0         106   
200          141         mpfi  3.78   3.15               9.5         114   

    peak_rpm  city_mpg  highway_mpg  price  
0       5000        21           27  13495  
1       5000        21           27  16500  
2       5000        19           26  16500  
3       5500        24           30  13950  
4       5500        18           22  17450  
..       ...       ...          ...    ...  
196     5400        23           28  16845  
197     5300        19           25  19045  
198     5500        18           23  21485  
199     4800        26           27  22470  
200     5400        19           25  22625  

[201 rows x 25 columns]